### ISSUE TITLE
SWIG 4.2+ python bindings of long double macro produces code that fails to compile

### ISSUE THREAD

**Issue by aymanhab** [swig/swig#3129]
Upgrading the swig version from 4.1.1 to 4.2 runs into a problem because of the macro below (it appears in a header file from a third party library that I can't change), but I get the same behavior inserting the same line in my .i file:

#define MY_PI 3.1415926535897L

The resulting python code doesn't compile:

  SWIG_Python_SetConstant(d, "MY_PI",SWIG_NewPointerObj(SWIG_as_voidptr(&3.1415926535897),SWIGTYPE_p_long_double, 0 ));

The compilation error follows: 

'&' on constant (C2101 in visual studio).

I'm on windows using VisualStudio 2022 Community Edition and Python 3.9. Using the latest swig release and a later python produces the same behavior.

**Comment by ojwb** [comment]
`git bisect` says this changed in 7ba44dc62de77c23ed67ce4578e1042f7f4e292d.  The relevant part of that change here is that 4.2.0 now correctly deduces `3.1415926535897L` as having type `long double`, whereas it was incorrectly deduced as `double` before.

However Python doesn't have a suitable `long double` typemap so it tries to wrap it as an opaque type.  Unfortunately that's not going to work as opaque types are wrapped via a pointer, but there's nothing we can take an address of here.

Options I can see:

* Add `%ignore MY_PI;` before the `%include` for this header.  `MY_PI` won't get wrapped, but it's redundant anyway as Python has `math.pi` which gives has more precise value of PI.  (Aside: it's curious `MY_PI` is specified as a `long double` but its value has less precision than an IEEE `double`!)
* Add `%warnfilter(302) MY_PI;` and `%constant double MY_PI;` before the `%include` for this header.  `MY_PI` will be wrapped as a `double` like it was by SWIG < 4.2.0.
* Write a suitable `long double` typemap for SWIG - I don't think Python has `long double` type, but it could probably be mapped to an extended precision type (numpy or something?)
* Get SWIG to wrap a `long double` constant as a Python `float` automatically like SWIG < 4.2.0 did.  This seems a bad idea as in general it will lose precision on the value.  I'd argue that the change you've run into is a bug fix.
* Find some way to get SWIG to ignore such constants by default rather than try to wrap them as opaque types.  Not sure how to achieve that though.

The first two options should work equally well with SWIG < 4.2.0 too if you care about compatibility with older versions.

**Comment by vadz** [comment]
IMHO mapping `long double` to `double` in Python would be a simple and useful stopgap solution until something better can be found (if it's even needed).

**Comment by aymanhab** [comment]
Thanks @ojwb and @vadz I agree that mapping long double to double in python would be the best available option considering the available types across languages supported by SWIG. 

The example above was intentionally simplified, the actual macro has 20+ significant digits and there're tens of these macros (used by this scientific computations package) so custom solutions for each macro would be an overkill. I'll try to ignore the constants or if not find/write a typemap to map long double to doubles in python.

**Comment by ojwb** [comment]
If you just want a simple way to say "just treat `long double` as `double`" then:

```
%apply double { long double };
```

I'm going to close this as there are multiple solutions offered above for the specific situation, and we already have #2964 for the general issue of support for wrapping `long double` constants.
