### ISSUE TITLE
Generated code contains use of nonexistent object.__getattr__ method.

### ISSUE THREAD

**Issue by nezumisama** [swig/swig#588]
Python code generated from *Source/Modules/python.cxx* contains use of nonexistent *object.\__getattr__* method. In Python3 the object type doesn't have this method, it has *\__getattribute__*, which can be used instead.

**Comment by ahnolds** [comment]
Umm, am I missing something?  https://docs.python.org/3/reference/datamodel.html#object.__getattr__

**Comment by nezumisama** [comment]
I think in this fragment, **object** is used as a placeholder instance name. Otherwise, it's incorrect. The built-in type **object** does not have the **__getattr__** method, it has only **__getattribute__**.

    $ python3
    Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
    [GCC 5.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> object.__getattr__
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: type object 'object' has no attribute '__getattr__'
    >>> object.__getattribute__
    <slot wrapper '__getattribute__' of 'object' objects>

**Comment by ahrbe1** [comment]
I can confirm this is an issue. A project I work on uses swig to generate python bindings with python 2.7.10. The unit tests we wrote for our API bindings worked fine under swig 3.0.7. After an update to 3.0.8, most of our tests are failing due to this issue. Even trying to instantiate any of our API objects fails.

**Comment by ahnolds** [comment]
Can you share a unit test where this fails?  Obviously it passes all the tests we have...

**Comment by wsfulton** [comment]
Please include the command line options that you use to invoke SWIG with the test.

**Comment by ahrbe1** [comment]
[swig-308-test.zip](https://github.com/swig/swig/files/102117/swig-308-test.zip)

Attached. You may need to edit the included build.sh script to suit your environment. I tested this both with 3.0.7 and 3.0.8.

**Comment by ahnolds** [comment]
#584 resolves this (at least, the case that @ahrbe1 has).  @nezumisama does whatever was breaking for you also rely on wrapping a class named "Exception"?

Note that the point is still legitimate though - while `object.__setattr__` exists in both python2 and python3, the corresponding get function does seem to be `object.__getattribute__`, and `object.__getattr__` doesn't seem to be defined.  I'll try switching it and see if it passes the unit tests as a first check

**Comment by ahnolds** [comment]
Switching to `__getattribute__` doesn't seem like a good solution.  It passes most of the tests (I'm still waiting on Appveyor to finish), but messes up the `-classic` build quite badly.  In particular, lots of things go into an infinite recursion (which is conveniently broken with an exception by Python's recursion depth limit) looking for the __coerce__ method which doesn't exist on an old-style class where it isn't explicitly defined.

It looks like the call to `object.__getatt__` was added by @diorcety in #232 commit 558af63.  Maybe he could shed some light on why that got added.

**Comment by diorcety** [comment]
Hi
If you extend a class generated by swig and try to read/set a property defined in the extended class, without this patch it will not work.

**Comment by diorcety** [comment]
Maybe the patch is not correct in all the "mode" supported by swig, i'm sorry for that

**Comment by wsfulton** [comment]
The AttributeError message has been improved by applying patch #598.
