### ISSUE TITLE
Unable to compile on Node V0.12^

### ISSUE THREAD

**Issue by faridz88** [swig/swig#766]
Hi
The generated cxx code for node js does not compile on Node V0.12, V4.4.7 and v6.3.1
Compile Errors:
```
In file included from /root/.node-gyp/6.3.1/include/node/node.h:42:0,
                 from ../modsecurity/modsecurity_wrap.cxx:171:
/root/.node-gyp/6.3.1/include/node/v8.h: In function ‘SwigV8ReturnValue _wrap_msc_rules_add(const SwigV8Arguments&)’:
/root/.node-gyp/6.3.1/include/node/v8.h:904:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../modsecurity/modsecurity_wrap.cxx:19659:21: error: within this context
     v8::HandleScope scope;
                     ^
../modsecurity/modsecurity_wrap.cxx:19661:21: error: ‘class v8::HandleScope’ has no member named ‘Close’
     args[2] = scope.Close(v8::String::New(*(arg3)));
                     ^
../modsecurity/modsecurity_wrap.cxx:19661:27: error: ‘New’ is not a member of ‘v8::String’
     args[2] = scope.Close(v8::String::New(*(arg3)));
```

Looking at error lines in cxx file and referring to [this link](https://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/
), seems like it is using Node 0.10 API. Setting `-DV8_VERSION` had no effect.

in modsecurity_wrap.cxx:19607 :
```C++
static SwigV8ReturnValue _wrap_msc_rules_add_file(const SwigV8Arguments &args) {
  SWIGV8_HANDLESCOPE();

  v8::Handle<v8::Value> jsresult;
  modsecurity::Rules *arg1 = (modsecurity::Rules *) 0 ;
```

**Comment by ojwb** [comment]
The testsuite passes for me with currently SWIG git master, and I'm using:

```
$ nodejs --version
v4.4.7
```

You don't appear to specify the SWIG version you're using, but try a newer version if it's not the latest.

If it's still failing, please provide a small, self-contained testcase.
