### ISSUE TITLE
M2Crypto bindings no longer functional with swig 3.0.5

### ISSUE THREAD

**Issue by DimStar77** [swig/swig#344]
See also the M2Crypto issue 
https://github.com/martinpaljak/M2Crypto/issues/60
as well as https://bugzilla.suse.com/show_bug.cgi?id=917759

With Swig 3.0.5, the bindings for openssl created using M2Crypto are no longer functional:

<pre>
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import M2Crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Kristofer/ExternalUsers/kyounger/Projects/tioga-flask-mini/venv/lib/python2.7/site-packages/M2Crypto/__init__.py", line 24, in <module>
    import ASN1
  File "/Volumes/Kristofer/ExternalUsers/kyounger/Projects/tioga-flask-mini/venv/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 12, in <module>
    import BIO
  File "/Volumes/Kristofer/ExternalUsers/kyounger/Projects/tioga-flask-mini/venv/lib/python2.7/site-packages/M2Crypto/BIO.py", line 221, in <module>
    class CipherStream(BIO):
  File "/Volumes/Kristofer/ExternalUsers/kyounger/Projects/tioga-flask-mini/venv/lib/python2.7/site-packages/M2Crypto/BIO.py", line 227, in CipherStream
    SALT_LEN = m2.PKCS5_SALT_LEN
AttributeError: 'module' object has no attribute 'PKCS5_SALT_LEN'
</pre>

I attempted to bisect swig between 3.0.4 (working) and 3.0.5 and ended up on commit
commit c21e2423a02939d2a4bc02bdfaa5c3bed3be95b2
Author: Paweł Tomulik <ptomulik@meil.pw.edu.pl>
Date:   Sat Oct 25 22:56:41 2014 +0200

    make %constant directive to work with structs/classes

as being the first bad commit.

**Comment by DimStar77** [comment]
Some more digging:
it appears as if all %constant (and also #define, they seem to be treated equally) ARE exported, BUT:

%module _m2crypto
%constant int PKCS5_SALT_LEN=8;

will be provided as _m2crypto.PKCS5_SALT_LEN_swigconstant; previously, this was accessible as _m2crypto.PCKS5_SALT_LEN; considering that the most common usecase is importing a .h file full of #define, it is surprising to see that nobody else might have run into this issue.

**Comment by wsfulton** [comment]
Thanks for the bisect info... pinging @ptomulik

**Comment by ptomulik** [comment]
Hi,

AFAIR, the ``XYZ_swigconstant`` is a function which registers XYZ constant. This is used when python wrapper is generated with ``-builtin`` flag. The machinery is so constructed, that you'll probably not see the original ``XYZ`` constants in the generated shadow (python) files. They're loaded dynamically by the generated c/c++ wrappers.

I've just tried this example with ``master``:

```
// m2crypto.i
%module m2crypto
%constant int PKCS5_SALT_LEN=8;
```

```
# test.py
import m2crypto
print dir(m2crypto)
print m2crypto.PKCS5_SALT_LEN
```

which seems to work properly:

```
ptomulik@barakus:$ swig -python m2crypto.i && gcc m2crypto_wrap.c -shared -fPIC -o_m2crypto.so -I /usr/include/python2.7
ptomulik@barakus:$ python test.py 
['PKCS5_SALT_LEN', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_m2crypto', '_newclass', '_object', '_swig_getattr', '_swig_getattr_nondynamic', '_swig_property', '_swig_repr', '_swig_setattr', '_swig_setattr_nondynamic']
8
```

This works also with ``-builtin``. Could you provide a specific example (with the python runner) which doesn't work?

**Comment by ptomulik** [comment]
Another, question, is the leading underscore in your module name (``_m2crypto``) intenional?

**Comment by ptomulik** [comment]
Ok, I've took a look into your [M2Crypto](https://github.com/martinpaljak/M2Crypto) I'll leave a commend there.

**Comment by DimStar77** [comment]
@ptomulik Thanks for looking into it; so there must be something much more subtle wrong in the way M@Crypto has it's swig files prepared i'm afraid.

**Comment by wsfulton** [comment]
Looking at the M2Crypto build - https://github.com/martinpaljak/M2Crypto/blob/master/setup.py, -modern is passed to SWIG. Can you try with this option (we don't test this option regularly unfortunately).

**Comment by ojwb** [comment]
I'd argue it's pretty crazy that `-modern` isn't the default at this point.

According to the CHANGES entry for it:

```
            5. Added a -modern command-line flag that will cause
            SWIG to omit the cruft in the proxy modules that allows
            it to work with versions of Python prior to 2.2. The
            result is a simpler, cleaner and faster python proxy
            module, but one that requires Python 2.2 or greater. 
```

So by default, we're trying to create code which is compatible with Python 2.1, which last saw a release nearly 13 years ago.  I seriously doubt anybody has tested with Python 2.1 for many years, so it's very unlikely current SWIG generates code which works with it out of the box.

And due to this, we not testing an option which everybody probably ought to be using, and rely on those who actually are to file bug reports when we manage to break it and don't notice because we aren't testing with it.

**Comment by vadz** [comment]
The really crazy thing is the sheer number of variants of Python backend. There are at least `-builtin`, `-classic` and `-modern` which have to be multiplied by Python versions (at least 2.7 and 3.x) resulting in (again, *at least*) 6 combinations to test.

But then there are also `-classptr`, `-oldrepr`, `-keyword` and a number of `-noxxx` options which also modify the generated code in not completely obvious ways. This makes the code in `python.cxx` very difficult to understand and even more so to modify and makes exhaustive testing of it practically impossible.

I'd argue that `-builtin` and `-modern` should be the defaults and everything else should be at least deprecated and ideally just disappear.

**Comment by ojwb** [comment]
In your first paragraph, there's also not using any of those options, making the combinations at least 8.

ISTR from having looked at this before that there may be reasons why using `-builtin` won't work for everyone.

But certainly it would be easier to avoid any change potentially breaking some obscure combination if a lot of these options were permanently wired on or off.

Perhaps the biggest problem is that Marcelo wasn't always great at documenting why he added something (or indeed at documenting things he added at all in some cases), so it's not always clear what one of these options is really for, and what the full implications are of using it or not.

As an example, `-buildnone` eschews `Py_None` and builds its own replacement.  But there's no obvious rationale as to **why** this change might be desirable in the code, the documentation, the commit messages, or `CHANGES`.

After some digging in Google, I eventually turned up https://docs.python.org/2/faq/windows.html#how-can-i-embed-python-into-a-windows-application (see point 5).  So this particular option seems to be useful on Windows if you use a different compiler to build your code to that which was used to build the Python DLL.

**Comment by masterkorp** [comment]
Any status update on this issue ?

**Comment by wsfulton** [comment]
The discussion about having too many options is fair but is a distraction from the crux of this bug and I suggest is discussed on the swig-devel mailing list. I don't believe we have a test case that can reproduce the problem. Without a testcase, we can't investigate. I've tried using a combination of -modern and -builtin on the test case in the first post by @ptomulik which all work. Has it got something to do with the leading underscore in the module name _m2crypto?

**Comment by joejulian** [comment]
One difference I've noticed between how your example successfully works and how it's failing in M2Crypto is that you use the generated python file and M2Crypto loads the extension directly. That worked fine prior to cfaf2f9.

With the generated python file, it fails with:
```
>>> import _m2crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_m2crypto.py", line 108, in <module>
    class stack_st_OPENSSL_STRING(_object):
  File "_m2crypto.py", line 114, in stack_st_OPENSSL_STRING
    __swig_setmethods__["stack"] = __m2crypto.stack_st_OPENSSL_STRING_stack_set
NameError: name '_stack_st_OPENSSL_STRING__m2crypto' is not defined
```

Removing the underscore from the module name, however, does allow it to work correctly.

**Comment by ptomulik** [comment]
Yes, the main problem was that M2crypto imported the _m2crypto instead of m2crypto (shadow file). This was already discussed in https://github.com/martinpaljak/M2Crypto/issues/60

**Comment by ojwb** [comment]
@ptomulik If I follow correctly, this isn't a SWIG bug, and has now been addressed in m2crypto - is that correct?  If so, we can close this ticket.

**Comment by ptomulik** [comment]
Yes, I think so.

**Comment by wsfulton** [comment]
Fixed in SWIG by #631.
