### ISSUE TITLE
Build of dnf5 failed with SWIG 4.2.0

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2744]
I am testing rebuild of SWIG dependencies against version 4.2.0 in Fedora rawhide/40.

The build of `dnf5-5.1.9` is failing with this version.

```
dnf5-5.1.9/redhat-linux-build/bindings/python3/libdnf5/CMakeFiles/python3_repo.dir/repoPYTHON_wrap.cxx:5656:56: error: expected template-name before ‘<’ token
 5656 |     struct SwigPyMapIterator_T : SwigPyIteratorClosed_T<OutIterator, ValueType, FromOper>
      |                                                        ^
dnf5-5.1.9/redhat-linux-build/bindings/python3/libdnf5/CMakeFiles/python3_repo.dir/repoPYTHON_wrap.cxx:5656:56: error: expected ‘{’ before ‘<’ token
cc1plus: note: unrecognized command-line option ‘-Wno-sometimes-uninitialized’ may have been intended to silence earlier diagnostics
gmake[2]: *** [bindings/python3/libdnf5/CMakeFiles/python3_repo.dir/build.make:79: bindings/python3/libdnf5/CMakeFiles/python3_repo.dir/CMakeFiles/python3_repo.dir/repoPYTHON_wrap.cxx.o] Error 1
```
Complete build log is [here](https://download.copr.fedorainfracloud.org/results/jplesnik/swig-rebuild/fedora-rawhide-x86_64/04830452-player/builder-live.log.gz). Other information about the build can be found [here](https://copr.fedorainfracloud.org/coprs/jplesnik/swig-rebuild/build/6843308/).

**Comment by wsfulton** [comment]
This regression was introduced in 3a2318cb579edb3d1545210911b0058563521e3d. It seems to occur when using %import on a file that has a %template instantiation of a std::map.

Fix is in 95140fa417a4350e2a0ff51c6933667199949442 and I intend to include this into swig-4.2.1. 

Workaround in dnf5 is quite easy, just force the missing fragment as per the pull request https://github.com/rpm-software-management/dnf5/pull/1149.
