### ISSUE TITLE
Regression: class-nested enum as default argument

### ISSUE THREAD

**Issue by schwitrs** [swig/swig#3179]
Given the interface file (named test.i):
```
%module test

%inline%{

template<class X>
class A {

 public:
 enum anEnum {VAL1, VAL2} ;

 A(anEnum a=VAL1) {}
 
 };

%}

%template(Aint) A<int>;
```
swig 4.3.1 generates non-compiling code:
```
% swig -c++ -python -keyword -o test.cc test.i
% g++ -c -I /usr/include/python3.13 test.cc
test.cc: In function 'PyObject* _wrap_new_Aint(PyObject*, PyObject*, PyObject*)':
test.cc:3539:46: error: 'template<class X> class A' used without template arguments
 3539 |   A< int >::anEnum arg1 = (A< int >::anEnum) A::VAL1 ;
```
swig 4.0.2 works fine:
```
% swig -c++ -python -keyword -o test.cc test.i
% g++ -c -I /usr/include/python3.13 test.cc
```
Thank you for your assistance--
Charles

**Comment by ojwb** [comment]
@schwitrs You need to use triple backquotes around your reproducer code or else github eats things in `<`...`>` - I've added them for you this time.

`git bisect` shows this as introduced by a037e2f2e21884eb282b15da1478508d1cce5f86 - @wsfulton one of yours.

I wonder if the removal of `Append(typelist, val);` was accidental as there's no regression test or even an issue number to explain something it's meant to fix?

**Comment by wsfulton** [comment]
It was purposely removed as the template expansion was covered in the `Append(patchlist, val);` a few lines later. The test-suite had no diffs when removing this line, so I thought it was safe. However, it turns out that there's a bug in the expansion of the elements in the patchlist which I've now sorted out.
