### PR TITLE
Python: Fix build with 3.13 and limited abi<3.13

### LINKED ISSUE #3283: Py_LIMITED_API breaking change in 4.4.0 with python 3.13
Running swig 4.4.0 with python 3.13.2 and Py_LIMITED_API=0x03090000 I get the following errors.

```
.build\windows_release_real_wrapper\wrapper_scpi_wrap.cc(1453): error C3861: 'PyImport_AddModuleRef': identifier not found
.build\windows_release_real_wrapper\wrapper_scpi_wrap.cc(2125): error C3861: 'PyType_GetFullyQualifiedName': identifier not found
.build\windows_release_real_wrapper\wrapper_scpi_wrap.cc(2542): error C3861: 'PyType_GetFullyQualifiedName': identifier not found
.build\windows_release_real_wrapper\wrapper_scpi_wrap.cc(3275): error C3861: 'PyDict_GetItemStringRef': identifier not found
```

Running with swig 4.4.0 and python 3.12.11 does not produce this error.
Running with swig 4.3.1.post0 and 3.13.2 does not produce this error.

### PR DESCRIPTION
**Pull request by jschueller**
PyImport_AddModuleRef, PyType_GetFullyQualifiedName, PyDict_GetItemStringRef are available from >=3.13 but not if limited abi<3.13
https://docs.python.org/3/c-api/import.html#c.PyImport_AddModuleRef

introduced in https://github.com/swig/swig/pull/3233

Closes #3283

### CODE REVIEW

File: .github/workflows/linux.yml [hunk 1]
```diff
@@ -131,6 +131,11 @@ jobs:
         - SWIGLANG: python
           VER: '3.13'
           CSTD: gnu99
+        - SWIGLANG: python
+          VER: '3.13'
+          PY_ABI_VER: '3.9'
+          CSTD: gnu99
+          CPPFLAGS: '-O1'
```
Comment (ojwb) [inline .github/workflows/linux.yml]: `CPPFLAGS` is for C-preprocessor flags - `-O1` isn't a preprocessor flag, so should go in `CFLAGS` and/or `CXXFLAGS`.

Comment (jschueller) [reply .github/workflows/linux.yml]: done

File: Lib/python/pyhead.swg [hunk 2]
```diff
@@ -121,7 +121,9 @@ SWIG_Python_str_FromChar(const char *c)
 #endif
 
 #if PY_VERSION_HEX >= 0x03000000
-#if PY_VERSION_HEX < 0x030d00a6
+#if (PY_VERSION_HEX >= 0x030d00a6) && (!defined(Py_LIMITED_API) || Py_LIMITED_API+0 >= 0x030d0000)
```
Comment (wsfulton) [inline Lib/python/pyhead.swg]: Surely this should be:
```suggestion
#if (PY_VERSION_HEX >= 0x030d00a6) && (!defined(Py_LIMITED_API) || Py_LIMITED_API+0 >= 0x030d00a6)
```
and likewise for other similar cases below.

File: .github/workflows/linux.yml [hunk 3]
```diff
@@ -131,6 +131,12 @@ jobs:
         - SWIGLANG: python
           VER: '3.13'
           CSTD: gnu99
+        - SWIGLANG: python
+          VER: '3.13'
+          PY_ABI_VER: '3.9'
+          CSTD: gnu99
+          CFLAGS: '-O1'  # To avoid abi3audit false positive about Py_TYPE macro
+          CXXFLAGS: '-O1'
```
Comment (wsfulton) [inline .github/workflows/linux.yml]: Is it just me, but I cannot see this job in the CI actions!??

Comment (jschueller) [reply .github/workflows/linux.yml]: it seems github reorders finished jobs, so maybe it wasnt where you expected it to be in the list:
Screenshot_20251114_095640

File: Examples/test-suite/python/Makefile.in [hunk 4]
```diff
@@ -98,6 +97,7 @@ endif
 # Test requiring python-3.11 minimum if using Py_LIMITED_API
 ifeq (1,$(PY_ABI_311))
 CPP_TEST_CASES += pyabi311_bufferinterface
+CPP_TEST_CASES += python_pybuffer
```
Comment (wsfulton) [inline Examples/test-suite/python/Makefile.in:100]: The python_pybuffer test works before your patch is applied as follows:
```
$ cd Examples/test-suite/python
$ make python_pybuffer.cpptest PY_ABI_VER=3.9 CXXFLAGS=-O1
```
so the patch seems to be a regression - I don't expect to see any changes in this Makefile.in file which no longer runs this test if pyabi < 311.

File: .github/workflows/linux.yml [hunk 5]
```diff
@@ -131,6 +131,12 @@ jobs:
         - SWIGLANG: python
           VER: '3.13'
           CSTD: gnu99
+        - SWIGLANG: python
+          VER: '3.13'
+          PY_ABI_VER: '3.9'
+          CSTD: gnu99
+          CFLAGS: '-O1'  # To avoid abi3audit false positive about Py_TYPE macro
```
Comment (wsfulton) [inline .github/workflows/linux.yml]: Handy test hack, I hadn't thought of that :)

File: Examples/test-suite/python/Makefile.in (hunk 4 above)
Comment (jschueller) [reply Examples/test-suite/python/Makefile.in:100]: no, this fails with python >=3.13 / abi<3.11
```
python_pybuffer_wrap.cxx:3630:2: error: #error "The old Buffer Protocol was removed in python-3.13 and is only part of the stable ABI from python-3.11"
 3630 | #error "The old Buffer Protocol was removed in python-3.13 and is only part of the stable ABI from python-3.11"
      |  ^~~~~
```

I tried to revert that commit to prove my point:
https://github.com/swig/swig/actions/runs/19375319782/job/55441156831

File: .github/workflows/linux.yml (hunk 5 above)
Comment (jschueller) [reply .github/workflows/linux.yml]: yes, I noticed this by accident

Comment (jschueller) [reply .github/workflows/linux.yml]: note that this is not needed anymore with the latest version

File: Examples/test-suite/python/Makefile.in (hunk 4 above)
Comment (wsfulton) [reply Examples/test-suite/python/Makefile.in:100]: I see, I was using python-3.12 when I checked, not python-3.13. Nevertheless, I was trying to point out that the patch has stopped testing the python_pybuffer testcase for pyabi<3.11. We need that testing back, in particular in the **python 3.8 abi=3.5 gcc** job. This job tests the old buffer protocol (that is in the stable ABI, even though deprecated, until it was removed in 3.13). We need to continue testing it. 5ead5779162222749beaddbc2ca7518c1e814244 restores the testing.

**Comment by wsfulton** [comment]
I've committed these commits to master as be1ff429dc3021d9adbf29297ad6ed4909d66361...5ead5779162222749beaddbc2ca7518c1e814244. Thanks. Due to the severity of this, I'll be looking at releasing a swig-4.4.1 patch release in the coming days with this fix.

**Comment by jschueller** [comment]
thanks

**Comment by jschueller** [comment]
hi, I see the new release on SF but not on github, maybe you forgot to push the tag in git ?

**Comment by wsfulton** [comment]
I have only just this minute sent out the comms, pushed the docs, tags, web updates etc to complete the release.
