### ISSUE TITLE
SWIG 4.4.0 breaks build of plplot python bindings

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#3262]
The build of plplot-5.15.0 is failing against future SWIG 4.4.0 (https://github.com/swig/swig/commit/b440f9eeb9abd0c012f0486613a53805e6dd1897) in Fedora rawhide/44.

```
/builddir/build/BUILD/plplot-5.15.0-build/plplot-5.15.0/redhat-linux-build/bindings/python/plplotcPYTHON_wrap.c: In function ‘SWIG_mod_exec’:
/builddir/build/BUILD/plplot-5.15.0-build/plplot-5.15.0/redhat-linux-build/bindings/python/plplotcPYTHON_wrap.c:23946:3: error: returning ‘void *’ from a function with return type ‘int’ makes integer from pointer without a cast [-Wint-conversion]
23946 |   import_array();
      |   ^~~~~~~~~~~~
gmake[2]: *** [bindings/python/CMakeFiles/plplotc.dir/build.make:82: bindings/python/CMakeFiles/plplotc.dir/plplotcPYTHON_wrap.c.o] Error 1
```

The complete log could be found here:
https://jplesnik.fedorapeople.org/swig44/plplot-builder-live.log

It seems similar to issue https://github.com/swig/swig/issues/3261

**Comment by ojwb** [comment]
I think it's exactly the same problem.

Looks like `import_array()` may be a numpy thing.

**Comment by wsfulton** [comment]
@jplesnik, can you try a similar fix to https://github.com/pygsl/pygsl/issues/90, as referenced in #3261? That is call `import_array1` instead of `import_array`, (barely) mentioned in numpy docs https://numpy.org/devdocs/reference/c-api/array.html.

**Comment by jplesnik** [comment]
@wsfulton The fix used by pygsl works also for plplot. 
The build is https://copr.fedorainfracloud.org/coprs/jplesnik/swig-test/build/9686989/

I'll report it to plplot upstream and recommend them the solution.

**Comment by jplesnik** [comment]
Reported to plplot upstream
https://sourceforge.net/p/plplot/support-requests/56/

**Comment by jplesnik** [comment]
The fix does not work with SWIG 4.3.0.

```
/builddir/build/BUILD/plplot-5.15.0-build/plplot-5.15.0/redhat-linux-build/bindings/python/plplotcPYTHON_wrap.c: In function ‘PyInit__plplotc’:
/builddir/build/BUILD/plplot-5.15.0-build/plplot-5.15.0/redhat-linux-build/bindings/python/plplotcPYTHON_wrap.c:23561:17: error: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer without a cast [-Wint-conversion]
23561 |   import_array1(-1);
      |                 ^
/usr/lib64/python3.14/site-packages/numpy/_core/include/numpy/__multiarray_api.h:1608:12: note: in definition of macro ‘import_array1’
 1608 |     return ret; \
      |            ^~~
```

https://copr.fedorainfracloud.org/coprs/jplesnik/swig-rebuild/build/9686988/

For `pygsl`, there is a workaround in spec file:
https://src.fedoraproject.org/rpms/pygsl/blob/rawhide/f/pygsl.spec#_108

**Comment by ojwb** [comment]
> The fix does not work with SWIG 4.3.0.

That's not a surprise - the function this code gets generated into has different return types with SWIG 4.3.0 vs 4.4.0 so the choice of `import_array` vs `import_array1` is really going to need to be conditional on the SWIG version to have something which works with both.  You should be able to check e.g.:

```
#if SWIG_VERSION >= 0x040400 // SWIG >= 4.4.0
```

Note that this needs to be a SWIG-time conditional (not get generated in the C/C++ wrapper file and evaluated by the C/C++ compiler).

**Comment by jplesnik** [comment]
@ojwb Thanks for the solution. I updated the patch and build passed with both version. Updated patch was added to plplot ticket.
