### ISSUE TITLE
Invalid swigRelease implementation when using %typemap(javafinalize)

### ISSUE THREAD

**Issue by VirtualTim** [swig/swig#2918]
I'm seeing this following issue when attempting to update SWIG 4.0.2 -> SWIG 4.2.0 (Edit: same behaviour with 4.1.1 and 4.3.0). My input is C++11, output Java.

Build Error:
```
test.java:36: error: cannot find symbol
       obj.delete();
          ^
```

.i file contains:
```
%typemap(javainterfaces) test "java.lang.AutoCloseable"

%typemap(javafinalize) test 
%{
  protected void finalize() {
    close();
  }
%}
```
(Note that I inherited this file, so can't easily explain why it is the way it is)

This generated Java code like:
```java
public class test implements java.lang.AutoCloseable {
  protected static long swigRelease(test obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }
}
```

I don't know where this `delete` method is supposed to come from.
This function (`swigRelease`) did not get generated for SWIG 4.0.

**Comment by ojwb** [comment]
Looks to be introduced by bf761998ed481821997e7c65f5d3e6acdf2eaf03 (previously the `obj.delete();` code was in a `javarelease` typemap).  @wsfulton That change was yours...

**Comment by VirtualTim** [comment]
Still an issue with SWIG 4.3.0.

**Comment by wsfulton** [comment]
The default typemap that provides `finalize` is:

https://github.com/swig/swig/blob/v4.3.0/Lib/java/java.swg#L1306-L1311

and your javafinalize typemap overrides this. The default `delete` implementation is in the javadestruct typemap:

https://github.com/swig/swig/blob/v4.3.0/Lib/java/java.swg#L1347-L1366

Your code must override this typemap if the delete method is not being generated. Look for instances of javadestruct and javadestruct_derived (if `test` is a derived class). Given your code is making changes to the default finalizers, you must also make appropriate changes for >= swig-4.1 to work. Copy the javabody/javabody_derived typemaps from java.swg and provide your own implementation of the swigRelease function to not call `delete` (probably you want just call close() like your finalize method does??!).
