### ISSUE TITLE
SWIG generated Python code should be flake8 clean

### ISSUE THREAD

**Issue by bje-** [swig/swig#1221]
Python scripts generated with SWIG 3.0.8 produce a lot of warnings from `flake8` about Python style issues (eg, whitespace around operators). Some simple changes would cut down a lot of the noise.

**Comment by ojwb** [comment]
Note that 3.0.8 isn't the latest release, and there's significant work on master since 3.0.12.

But assuming this hasn't been addressed since, a patch would be great.

**Comment by bje-** [comment]
I tried running SWIG (master) over the `example.i` example in the manual and then running `flake8` over the generated `example.py` script. The results are:

```
example.py:51:1: E302 expected 2 blank lines, found 1
example.py:90:1: E305 expected 2 blank lines after class or function definition, found 1
example.py:101:1: E305 expected 2 blank lines after class or function definition, found 0
example.py:101:1: F811 redefinition of unused 'fact' from line 99
example.py:103:1: E302 expected 2 blank lines, found 1
example.py:105:1: E305 expected 2 blank lines after class or function definition, found 0
example.py:105:1: F811 redefinition of unused 'my_mod' from line 103
example.py:109:1: W391 blank line at end of file
```

It would be good if this simple example could be flake8 clean. That would likely be a good starting point to improving the generated scripts in real projects.

**Comment by ojwb** [comment]
`flake8` still moans for `Examples/python/simple` with git master.

Needs somebody who cares about flake8 to submit patches to either adjust the generated code or suppress the warnings which aren't useful for generated code.

**Comment by wsfulton** [comment]
Flake8 is near enough a wrapper around pyflakes and pycodestyle. The test-suite is actually pycodestyle free as we install it and use it when using GHA in our CI. Detection of pycodestyle is done in configure.ac and used in the test-suite where you can see the warnings we have suppressed: https://github.com/swig/swig/blob/9eb75a0c07f2f847caa1cae80ef162e8b99d29d4/Examples/test-suite/python/Makefile.in#L14-L15.

I just tried using flake8 and there a small number of additional warnings in the test-suite but most test-cases are clean. So, there isn't actually much work to be done here unless one thinks that removing the suppressions and fixing things like blanks is important. What would seem useful to do is to upgrade our *tool of choice* from pycodestyle to flake8 and fix the few additional warnings. Making the linting tool more configurable would also be useful.

**Comment by bje-** [comment]
Sounds good.
