### ISSUE TITLE
-autorename (Ruby) collides std::vector partial specializations since 4.5.0, silently dropping vector<bool>

### ISSUE THREAD

**Issue by blowekamp** [swig/swig#3546]
### Regression

Since SWIG 4.5.0, using `-ruby -autorename` together with `%include <std_vector.i>` causes the `bool`, `T*` and `T const*` partial specializations of `std::vector` to be silently dropped, because they all camelcase to the same default name `Vector` as the primary template and lose to it as duplicate identifiers (`Warning 302: Redefinition of identifier 'Vector' ... ignored`).

Concretely, `%template(VectorBool) vector<bool>;` compiles without error but produces **no wrapper at all** for `VectorBool` under `-autorename`, since `vector<bool, _Alloc>`'s class definition was already dropped earlier while parsing `std_vector.i`.

### Repro
```swig
%module(directors="1") test
%include <std_vector.i>
namespace std {
  %template(VectorBool) vector<bool>;
}
```
```
swig -ruby -autorename -c++ test.i
```
Output includes:
```
Warning 302: Redefinition of identifier 'Vector' (Renamed from 'vector') as std::vector< bool,_Alloc > ignored,
Warning 302: previous definition of 'Vector' (Renamed from 'vector') as std::vector.
```
and the generated wrapper defines no `VectorBool`/`Vector` methods for the bool specialization.

### Bisected to
`ce06e2fc13a3cac4fe1aa698ba8889f38c501ee7` — "Advanced %rename fixes for templates" (first in 4.5.0).

That commit changed `apply_rename()` in `Source/Swig/naming.c` to strip template arguments from `name` before substituting it into a `%s`-style rename format:
```c
String *template_name = SwigType_istemplate_templateprefix(name);
String *name_simple = template_name ? template_name : name;
...
result = NewStringf(fmt, name_simple);
```
Ruby's `-autorename` applies `%rename("%(camelcase)s", %$isclass) "";` globally, which is exactly this code path. Before the change, `%s` received the full templated name (distinguishing `vector<bool,...>` from `vector<T*,...>` etc.), so each specialization got a distinct default identifier. Now they all reduce to the same base name `vector` → `Vector`, and only the first-parsed one survives.

### Impact / workaround
Discovered via SimpleITK's Ruby wrapping build (upgrading SWIG 4.4.0 → 4.5.0 broke `VectorBool`, `NameError: uninitialized constant`). Worked around it there by explicitly `%rename`-ing the specializations before `%include <std_vector.i>` so autorename no longer needs to invent colliding names:
- Fix: https://github.com/SimpleITK/SimpleITK/pull/2677
- Backport: https://github.com/SimpleITK/SimpleITK/pull/2675

Filing upstream since this affects any `-autorename` Ruby user of `std_vector.i` (or presumably other stdlib containers with partial specializations), not just SimpleITK.

**Comment by wsfulton** [comment]
I'll include the fix here in the swig-4.5.1 release.

**Comment by blowekamp** [comment]
@wsfulton Thank you. I have confirmed the fix works for my project.
