### ISSUE TITLE
[PYTHON] getting a class member that doesn't exists, reports an ambiguous error

### ISSUE THREAD

**Issue by daniele-niero** [swig/swig#553]
Imagine to have wrapped a class and from python code we make a syntax error trying to access one of its methods or attributes.

for example in a hypothetical Vec3 class we call:

myVec = Vec3()
print myVec.lenght()

"lenght" is misspelled and python simply knows that it is not a valid Vec3 member.
The expected error should be this:

```
AttributeError: 'Vec3' object has no attribute 'lenght'
```

but for some reason, the swig wrapper makes python to report this instead:

```
AttributeError: 'Vec3' object has no attribute __getattr__
```

which doesn't tell us anything about the error and mistake we have made.

Swig version is 3.0.7. 
Python 2.7
tested on windows

**Comment by ojwb** [comment]
Running swig with the `-modern` option will probably solve this.

Using `-modern` stops the generated code from work with Python < 2.2, but that's an irrelevant restriction in 2015.  SWIG really ought to default to generating modern classes, rather than everyone wrapping Python code having to discover this is what they really want for themselves.

**Comment by daniele-niero** [comment]
Yes, that fixed the problem.
Many thanks.

**Comment by ojwb** [comment]
Since SWIG 4.0.0 `-modern` is always on so we'll always give the more useful error message - closing.
