### ISSUE TITLE
Non-compilable wrap code when using static_cast<>

### ISSUE THREAD

**Issue by lluisalemanypuig** [swig/swig#1677]
While using SWIG 4.0.1, I may have found a way for which SWIG fails to make wrap code compilable by `g++`. This is related to another issue that I have also posted, but independent from it, so I post this here.

In short, I have this header file, which I called `my_enum.hpp`:
```
#pragma once
enum class my_enum {
     type_0, type_1, type_2, type_3,
     type_4, type_5, type_6, type_7, type_8
};
typedef std::bitset<static_cast<uint32_t>(my_enum::type_8)> type;
// I added the following two functions so as to provide a usage example.
type classify(int a) {
	type k(0);
	k.set(a, true);
	return k;
}
bool has_type(const type& T, const my_enum& t) {
	return T[static_cast<uint32_t>(t)];
}
```
This code is simple enough: a simple `enum class`, a `std::bitset`, and two very small functions. The code above can be used with the following minimal example:
```
#include <iostream>
#include "my_enum.hpp"
int main() {
    std::cout << type().size() << std::endl;
    type t = classify(5);
    std::cout << has_type(t, my_enum::type_8) << std::endl;
}
```
which compiles perfectly with `g++` (9.2.0).

Now, although SWIG (4.0.1) does not crash when making wrap code for `my_enum.i`:
```
%module my_enum
%{
#include "my_enum.hpp"
%}
%include "my_enum.hpp"
```
using the command `swig -Wall -c++ -python -py3 my_enum.i`, the wrap code is not compilable by `g++` (9.2.0). The errors issued by the compiler are:
```
my_enum_wrap.cxx: In function ‘PyObject* _wrap_has_type(PyObject*, PyObject*)’:
my_enum_wrap.cxx:2988:80: error: template argument 1 is invalid
 2988 |   result = (bool)has_type((std::bitset< static_cast< uint32_t > (enum my_enum::type_8) > const &)*arg1,(enum my_enum const &)*arg2);
      |                                                                                ^~~~~~
my_enum_wrap.cxx:2988:88: error: expected primary-expression before ‘>’ token
 2988 |   result = (bool)has_type((std::bitset< static_cast< uint32_t > (enum my_enum::type_8) > const &)*arg1,(enum my_enum const &)*arg2);
      |                                                                                        ^
my_enum_wrap.cxx:2988:90: error: expected primary-expression before ‘const’
 2988 |   result = (bool)has_type((std::bitset< static_cast< uint32_t > (enum my_enum::type_8) > const &)*arg1,(enum my_enum const &)*arg2);
      |                                                                                          ^~~~~
```
The wrap file generated by SWIG (4.0.1) contains the line:
```
result = (bool)has_type((std::bitset< static_cast< uint32_t > (enum __type::type_8) ....;
```
which is what is causing `g++` not to compile the file. If I replace that piece of code (line `2988` in my generated file) with:
```
result = (bool)has_type((std::bitset< static_cast< uint32_t > (__type::type_8) ...
```
(the `enum` keyword inside the `static_cast<uint32_t>()` has been removed) the code compiles perfectly.

I hope to have described the problem clearly and to have provided enough instructions for its reproducibility.

**Comment by ojwb** [comment]
I think this may be the same problem as #675.

**Comment by lluisalemanypuig** [comment]
Yes, the two are related. However, while in issue #675 the keyword `enum` appears within a custom class template
```C++
DispatcherClientServer< enum DispatchMode::Process > *
```
which makes `g++ -std=c++17` (version 9.2.0) fail to compile the wrap code, removing it does not fix the error. I mean: after calling `swig -Wall -c++ -python -py3 ReactHandler.i` with the contents of the `.i` file copied verbatim from issue #675, the wrap code contains a malformed expression (the one above) but after fixing it (by removing the `enum` keyword) the code is still not compilable. `g++` seems to complain about `DispatcherClientServer` not declared (error messages at the end). Now, in some cases the `<enum ...>` is allowed, and in others it is not, e.g.:
```C++
#include <iostream>
#include <vector>
#include <bitset>
using namespace std;
enum class asdf { t0, t1, t2, t3, t4 };
template<class T>
class dummy {
	public:
		dummy(const T& val) {value = val;}
		~dummy() {}
	private:
		T value;
};
int main() {
	// allowed
	vector< enum asdf > v(10);
	// interestingly, allowed
	dummy< enum asdf > d(asdf::t2);
	//                          \/ not allowed \/
	bitset<static_cast<uint32_t>(enum asdf::t3)> bs;
}
```
While sometimes `dummy< enum asdf >` is not allowed (as seen in issue #675) I do not think `static_cast<uint32_t>(enum asdf::t3)` is ever allowed. It is quite likely that `static_cast<uint32_t>(enum asdf::t3)` is always forbidden, hence making the two issues a bit different.

(I hope to have made a strong enough point about the two issues being different. But, since I'm not a C++ expert and I don't know the inner workings of SWIG the two issues could actually be the same. If so, should the post be removed?.)


Error messages mentioned above:

**Comment by ojwb** [comment]
> (I hope to have made a strong enough point about the two issues being different. But, since I'm not a C++ expert and I don't know the inner workings of SWIG the two issues could actually be the same. If so, should the post be removed?.)

I think it makes sense to keep both open unless we sure they're the same.

Mostly it seemed useful to note a ticket which seemed likely to be related.

**Comment by lluisalemanypuig** [comment]
Yes. Also, you'll be able to make sure that both are fixed :)

I removed std::bitset<> from the title of the issue and replaced it with static_cast<> since it is what is actually causing the bugs.
