### ISSUE TITLE
Removal of SWIG_Python_TypeError in SWIG 4.4.0 breaks build of subversion python bindings

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#3260]
The build of subversion-1.14.5 is failing against future SWIG 4.4.0 (b440f9eeb) in Fedora rawhide/44.

```
subversion/bindings/swig/python/svn_client.c: In function '_wrap_svn_client_get_simple_prompt_provider':
subversion/bindings/swig/python/svn_client.c:4259:7: error: implicit declaration of function 'SWIG_Python_TypeError'; did you mean 'SWIG_Python_TypeQuery'? [-Wimplicit-function-declaration]
 4259 |       SWIG_Python_TypeError(SWIG_TypePrettyName(SWIGTYPE_p_apr_pool_t), obj2);
      |       ^~~~~~~~~~~~~~~~~~~~~
      |       SWIG_Python_TypeQuery
make: *** [build-outputs.mk:2367: subversion/bindings/swig/python/svn_client.lo] Error 1
```

The complete log could be found here:
https://jplesnik.fedorapeople.org/swig44/subversion-builder-live.log

The failure is caused by change in commit 9c2a1bc39c43dfe8958af36a5168412c67b467a9.

Could you please help me to find a fix for it?

**Comment by ojwb** [comment]
_Repeating my answer from the mailing list:_

`SWIG_Python_TypeError` was removed in 9c2a1bc39c43dfe8958af36a5168412c67b467a9 as "not used".  Not sure what the replacement in user typemaps would be.  We probably should note this removal in `CHANGES.current` along with a suggestion for how to deal with such uses.  @wsfulton ?

**Comment by wsfulton** [comment]
`SWIG_Python_TypeError` was part of an API that SWIG used before the major overhaul of typemaps back in 2005 in 7e5e4fd1f9c8adfcd0eb1328e35143e110e115ff. This way of reporting errors is long gone and a catchup is needed by subversion for some consistency in error handling as I can see just the one instance that has not been updated. Options are:

1. Copy and rename the deleted `SWIG_Python_TypeError` function and add into subversion code base to keep the error message the same.
2. Update the typemap as follows:
```diff
--- subversion-1.14.5/subversion/bindings/swig/include/svn_types.swg.original	2025-09-09 23:03:55.226572185 +0100
+++ subversion-1.14.5/subversion/bindings/swig/include/svn_types.swg	2025-09-09 23:04:44.216211917 +0100
@@ -601,7 +601,7 @@
 %typemap(in, noblock=1) apr_pool_t * {
   /* Verify that the user supplied a valid pool */
   if ($input != Py_None && $input != _global_py_pool) {
-    SWIG_Python_TypeError(SWIG_TypePrettyName($descriptor), $input);
+    SWIG_Error(SWIG_TypeError,  "expected '$type'");
     SWIG_arg_fail($svn_argnum);
     SWIG_fail;
   }
```
3. Use SWIG's modern approach:
```diff
--- subversion-1.14.5/subversion/bindings/swig/include/svn_types.swg.original	2025-09-09 23:03:55.226572185 +0100
+++ subversion-1.14.5/subversion/bindings/swig/include/svn_types.swg	2025-09-09 23:12:53.231858049 +0100
@@ -601,9 +601,7 @@
 %typemap(in, noblock=1) apr_pool_t * {
   /* Verify that the user supplied a valid pool */
   if ($input != Py_None && $input != _global_py_pool) {
-    SWIG_Python_TypeError(SWIG_TypePrettyName($descriptor), $input);
-    SWIG_arg_fail($svn_argnum);
-    SWIG_fail;
+    %argument_fail(SWIG_TypeError, "$type", $symname, $argnum); 
   }
 }
```

Example output of each:
1. `TypeError: argument number 1: a 'apr_pool_t *' is expected, 'int(1234)' is received`
2. `TypeError: argument number 1: expected 'apr_pool_t *'`
3. `TypeError: in method 'svn_client_get_simple_prompt_provider', argument 1 of type 'apr_pool_t *'`

Recommendations/commentary:
1. Not really recommended - the output from the error message is python version specific, is limited as it doesn't support builtin wrappers, limits usage to `-nofastunpack` due to usage of `$svn_argnum`, does not conform to PEP-737 and uses internal Python APIs so does not support the limited API.
2. Recommended approach to fit in with the `$svn_argnum` argument counting which I'd presume is deemed important in the subversion wrappers as described in subversion/bindings/swig/include/svn_global.swg.
3. Most compatible and consistent with modern SWIG error message output. The argument number may be different if the type is used in methods rather than global functions. I'd suggest only using this option though if `$svn_argnum` is removed/consistently updated in the other legacy SWIG API usage in subversion/bindings/swig/include/svn_global.swg and subversion/bindings/swig/include/svn_types.swg.

@jplesnik could you please try out option 2 and assuming the build passes, raise a subversion pull request with the patch. All 3 options should work with older SWIG versions (after version 1.3.32 released in 2007!).

**Comment by jplesnik** [comment]
@wsfulton I tested option [2](https://copr.fedorainfracloud.org/coprs/jplesnik/swig-test/build/9551014/) and [3](https://copr.fedorainfracloud.org/coprs/jplesnik/swig-test/build/9551024/) and both solved the build issue. Thank you for it.

I've send mail about it to `subversion` upstream.

**Comment by jschueller** [comment]
should the regression label and milestone be removed then ?

**Comment by ojwb** [comment]
It seems it's not just subversion still using `SWIG_Python_TypeError`:

https://codesearch.debian.net/search?q=%5CbSWIG_Python_TypeError%5Cb+-path%3A._wrap&literal=0&perpkg=1&page=1

I've excluded `*_wrap*`.  There look to be a few which are generated wrappers not using the `*_wrap.*` convention and one is SWIG itself, but at least s2geometry looks to be affected by this removal (and this is just from searching FOSS projects which are packaged in Debian).  So subversion isn't a lone outlier here.  Although this feature was replaced long ago, there's no warning to update uses from existing releases so it's not really surprising to find uses in the wild still.

Therefore I think it would be useful to at least give a suggestion in `CHANGES.current` for how to replace uses like we usually do when removing old features, so the milestone still seems appropriate.  It's indeed not a regression though since the removal was intentional.
