### ISSUE TITLE
duplicate definition of _wrap___lshift__  (regression from 4.2.0)

### ISSUE THREAD

**Issue by adl** [swig/swig#2845]
My project stopped compiling when I upgraded Swig from 4.2.0 to 4.2.1.   A quick scan of the changes between these two versions suggests that commit 344ca5fbc6a4bc2bec47a7795a3313eaf7040477 might be related.

Here is my interface file, shortened to keep only the relevant stuff:

```
%module impl

%feature("flatnested") spot::acc_cond::mark_t;

%inline %{
#include <iostream>

namespace spot
{
  class option_map
  {
  public:
    friend std::ostream&
      operator<<(std::ostream& os, const option_map& m);
  };

  class acc_cond
  {
  public:
    struct mark_t
    {
      mark_t operator<<(unsigned i) const;
      friend std::ostream& operator<<(std::ostream& os, mark_t m);
    };

  };

  std::ostream& operator<<(std::ostream& os, const acc_cond& acc);
}
%}
```
then:
```sh
% swig -c++ -python -O impl.i
% g++ -Wall -I/usr/include/python3.11 impl_wrap.cxx
impl_wrap.cxx:3827:22: error: redefinition of ‘PyObject* _wrap___lshift__(PyObject*, PyObject*)’
 3827 | SWIGINTERN PyObject *_wrap___lshift__(PyObject *self, PyObject *args) {
      |                      ^~~~~~~~~~~~~~~~
impl_wrap.cxx:3691:22: note: ‘PyObject* _wrap___lshift__(PyObject*, PyObject*)’ previously defined here
 3691 | SWIGINTERN PyObject *_wrap___lshift__(PyObject *self, PyObject *args) {
      |                      ^~~~~~~~~~~~~~~~
```

**Comment by ojwb** [comment]
> A quick scan of the changes between these two versions suggests that commit [344ca5f](https://github.com/swig/swig/commit/344ca5fbc6a4bc2bec47a7795a3313eaf7040477) might be related.

git bisect actually points to a6ab9145115aa124ff9c98e2b3c39fde9f205760 - @wsfulton that was yours.

**Comment by ojwb** [comment]
This seems to be specific to Python (I checked Ruby, Lua and PHP).  The `-O` option doesn't seem necessary to trigger it.

**Comment by wsfulton** [comment]
Java is okay too. The non-member function that this friend function defines is not being handled correctly with regard to function overloading. Until this is fixed, the workaround is to ignore the non-member function that the friend function defines, so add this before the flatnested feature:
```swig
%ignore spot::acc_cond::operator<<(std::ostream& os, mark_t m);
```
The above is technically wrong for ignoring this friend function and it should really be:
```swig
%ignore spot::operator<<(std::ostream& os, mark_t m);
```
and will be fixed too.
