### ISSUE TITLE
Forward declaration tests fail to build when using clang++ on OSX

### ISSUE THREAD

**Issue by marvingreenberg** [swig/swig#118]
The two tests template_using_directive_and_declaration_forward and using_directive_and_declaration_forward fail to build in the java test suite.  The code and errors are shown below.  This is for clang-500 on mavericks and clang-425 on mountain lion.

This seems to be a clang issue - this code builds fine on g++ 4.2 and 4.8.  li_std_vector also has a build failure.

```
214: namespace Outer1 {
215:   namespace Space1 {
216:     template<typename T> class Thing1;
217:   }
218: }
219: using namespace Outer1::Space1;
220: using Outer1::Space1::Thing1;
221: template<typename T> class Thing1 {};
222: void useit1(Thing1<int> t) {}
```
clang++ -c  -I/opt/local/include  template_using_directive_and_declaration_forward_wrap.cxx -I../../../../Examples/test-suite -I"/System/Library/Frameworks/JavaVM.framework/Headers" -I"/System/Library/Frameworks/JavaVM.framework/Headers"
template_using_directive_and_declaration_forward_wrap.cxx:222:6: error: variable has incomplete type 'void'
void useit1(Thing1<int> t) {}
     ^
template_using_directive_and_declaration_forward_wrap.cxx:222:13: error: reference to 'Thing1' is ambiguous
void useit1(Thing1<int> t) {}
            ^
template_using_directive_and_declaration_forward_wrap.cxx:220:23: note: candidate found by name lookup is 'Thing1'
using Outer1::Space1::Thing1;
                      ^
template_using_directive_and_declaration_forward_wrap.cxx:221:28: note: candidate found by name lookup is 'Thing1'
template<typename T> class Thing1 {};
                           ^

**Comment by ojwb** [comment]
The CI builds on OS X with clang are all passing, so looks like nobody actually followed up on this and closed it - doing so now.
