### ISSUE TITLE
Lua wrappers for C++ code no longer compile under Visual Studio 2010

### ISSUE THREAD

**Issue by amgaera** [swig/swig#152]
After updating from SWIG 2.0.12 to 3.0.0 Lua wrappers that are generated for C++ code no longer compile under Visual Studio 2010.

Steps to reproduce:
- open _Visual Studio Command Prompt (2010)_
- navigate to SWIG's `Examples\lua\class` directory
- execute the following commands:

```
swig.exe -c++ -lua example.i
cl.exe /c example_wrap.cxx /I path\to\lua\include\directory
```

Expected results:
- compilation succeeds

Actual results:
- compilation fails with the following error:

```
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

example_wrap.cxx
example_wrap.cxx(1722) : error C3861: 'snprintf': identifier not found
```

The above description assumes that _swigwin-3.0.0_ (executable and source code) is used.

As far as I can tell, other versions of Visual Studio are affected by this issue as well: the `snprintf` function is [still missing](http://blogs.msdn.com/b/vcblog/archive/2013/07/19/c99-library-support-in-visual-studio-2013.aspx) in VS  2013.
